// ACCOUNTS OF CUSTOMER CONSTS
export const CUSTOMER_ACCOUNTS_REQUEST = "CUSTOMER_ACCOUNTS_REQUEST";
export const CUSTOMER_ACCOUNTS_SUCCESS = "CUSTOMER_ACCOUNTS_SUCCESS";
export const CUSTOMER_ACCOUNTS_FAIL = "CUSTOMER_ACCOUNTS_FAIL";