// ACCOUNTS OF CUSTOMER CONSTANTS
export const CUSTOMER_ACCOUNTS_REQUEST = "CUSTOMER_ACCOUNTS_REQUEST";
export const CUSTOMER_ACCOUNTS_SUCCESS = "CUSTOMER_ACCOUNTS_SUCCESS";
export const CUSTOMER_ACCOUNTS_FAIL = "CUSTOMER_ACCOUNTS_FAIL";

// CREATE ACCOUNT CONSTANTS
export const ADD_ACCOUNT_REQUEST = "ADD_ACCOUNT_REQUEST";
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_FAIL = "ADD_ACCOUNT_FAIL";

