// Operations of account consts
export const ACCOUNT_OPERATIONS_REQUEST = "ACCOUNT_OPERATIONS_REQUEST";
export const ACCOUNT_OPERATIONS_SUCCESS = "ACCOUNT_OPERATIONS_SUCCESS";
export const ACCOUNT_OPERATIONS_FAIL = "ACCOUNT_OPERATIONS_FAIL";