// OPERATIONS OF ACCOUNT CONSTANTS
export const ACCOUNT_OPERATIONS_REQUEST = "ACCOUNT_OPERATIONS_REQUEST";
export const ACCOUNT_OPERATIONS_SUCCESS = "ACCOUNT_OPERATIONS_SUCCESS";
export const ACCOUNT_OPERATIONS_FAIL = "ACCOUNT_OPERATIONS_FAIL";

// ADD OPERATION CONSTANTS
export const ADD_OPERATION_REQUEST = "ADD_OPERATION_REQUEST";
export const ADD_OPERATION_SUCCESS = "ADD_OPERATION_SUCCESS";
export const ADD_OPERATION_FAIL = "ADD_OPERATION_FAIL";